using dotnet_backend.Models;
using dotnet_backend.DTOs;

namespace dotnet_backend.Mappers
{
    public static class FacultyMapper
    {
        public static FacultyDto ToDto(Faculty faculty)
        {
            if (faculty == null) return null;

            return new FacultyDto
            {
                FacultyId = faculty.FacultyId,
                PhotoUrl = faculty.PhotoUrl,
                FacultyName = faculty.FacultyName,
                TeachingSubject = faculty.TeachingSubject
            };
        }

        public static Faculty ToEntity(FacultyDto dto)
        {
            if (dto == null) return null;

            return new Faculty
            {
                // Do NOT set FacultyId because it's auto-generated by DB
                PhotoUrl = dto.PhotoUrl,
                FacultyName = dto.FacultyName,
                TeachingSubject = dto.TeachingSubject
            };
        }
    }
}
