using dotnet_backend.Models;
using dotnet_backend.DTOs;

namespace dotnet_backend.Mappers
{
    public static class GetInTouchMapper
    {
        public static GetInTouchDto ToDto(GetInTouch entity)
        {
            if (entity == null) return null;

            return new GetInTouchDto
            {
                ContactId = entity.ContactId,
                Name = entity.Name,
                Email = entity.Email,
                Message = entity.Message
            };
        }

        public static GetInTouch ToEntity(GetInTouchDto dto)
        {
            if (dto == null) return null;

            return new GetInTouch
            {
                // Do NOT set ContactId - auto-generated by DB
                Name = dto.Name,
                Email = dto.Email,
                Message = dto.Message
            };
        }
    }
}
