# Build step
FROM node:22-alpine as build
WORKDIR /app
COPY . .
RUN npm install && npm run build

# Nginx serving step
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
